FROM node:18-alpine as builder
WORKDIR /view
COPY package.json .
RUN npm install
COPY . .
EXPOSE 3000
RUN npm run build

FROM nginx:latest
COPY --from=builder /view/build /usr/share/nginx/html
EXPOSE 80
