name: commit-push-workflow

on: [push]

jobs:
  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install deps
        run: npm install
      # - name: save deps to artifact
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: node-modules-artifact
      #     path: node_modules
      - name: Run unit tests
        run: npm run test
  build-project:
    name: build project
    runs-on: ubuntu-latest
    needs: install-deps
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install deps
        run: npm install
      - name: Run build
        run: npm run build
      



