name: commit-push-workflow

on: [push]

jobs:
  build:
    name: build project
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install deps
        run: npm install
      - name: Run build
        run: npm run build
      - name: share artifact
        uses: actions/upload-artifact@v1
        with:
          name: project-build
          path: build 
  unit-test:
    name: unit test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: get artifact
        uses: actions/download-artifact@v1
        with:
          name: project-build
      - name: Run unit tests
        run: npm run test



