name: development-workflow

on: [push]

# on:
#   push:
#     branches: [ "develop" ]
#   pull_request:
#     # The branches below must be a subset of the branches above
#     branches: [ "develop" ]

jobs:
  eslint:
    name: Deploy to dev s3
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      
      # - name: Get npm cache directory
      #   id: npm-cache-dir
      #   run: |
      #     echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          # path: ${{ steps.npm-cache-dir.outputs.dir }}
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      # - name: Cache dependencies
      #   uses: actions/cache@v3
      #   id: npm-cache-step
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-build-${{ hashFiles('**/package.json') }}

      # - if: ${{ steps.npm-cache-step.outputs.cache-hit != 'true' }}
      #   name: Install dependencies
      #   run: npm install

      - name: Run unit tests
        run: npm run test
      
      - name: Run build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy
        run: aws s3 sync ./build s3://${{ secrets.AWS_BUCKET }}


