# reuse workflows to run basic tasks when raising PR
name: pull-request-develop-workflow

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: 
      - "develop"

jobs:
  sample-run:
    name: sample-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: ./.github/workflows/common-commit-tasks.yml



